### ISSUE TITLE
Min support

### ISSUE THREAD

**Issue by xxlabaza** [h3rald/min#1]
Is it possible to support the project? Some kind of donates via Bountysource or something like this...

**Comment by h3rald** [comment]
Thanks for the suggestion! I'll definitely look into it and I'll try to setup BountySpurce to provide an easy way to donate to this project :)

**Comment by h3rald** [comment]
Added [Donate](https://min-lang.org/donate/) page with links to BountySource and PayPal + BitCoin address.
