### ISSUE TITLE
Preferred method of concatenating strings?

### ISSUE THREAD

**Issue by mwgkgk** [h3rald/min#11]
What is the preferred method of concatenating two strings? Should we format them using interpolate? Is it reasonable to ask for `concat-str`? Maybe something I overlooked? Thank you :)

**Comment by h3rald** [comment]
I was debating on whether to add something like that or not... at present there is `interpolate` (`%`) but also `join`:

     (“This” “is” “a” “test”) “ “ join

It’s not as easy as a concat but it lets you customize the separator...

**Comment by mwgkgk** [comment]
`("asdf" "bsdf") "" join` seems reasonable! Concat would only be 1 argument shorter.

**Comment by baykus871** [comment]
You can define a symbol for concatenating. I'll show you how:
```
( symbol combine
  (quot :elems ==> string :result)
  (elems "" join @result)
) ::
```
OR
```
( =elems
  elems (quot) expect
  -> "" join
) :combine
```
