### ISSUE TITLE
help error

### ISSUE THREAD

**Issue by Econ441** [h3rald/min#119]
Tried this one:
`'*sbox/calamity help`

Help symbol gives error:
`(!) Undefined symbol or sigil: *sbox/calamity`

**Comment by h3rald** [comment]
I see what you are trying to do but I am not sure I wanna support it... invoke uses its own micro-syntax to access symbols within a dictionary/module.

How about this though (haven't tried it yet but hopefully it should work):

     (?calamity) sbox with

Basically it should execute the help command within the scope of sbox.

**Comment by Econ441** [comment]
Okay, thanks, it worked. 👍

**Comment by h3rald** [comment]
Ohhhh good! Finally I was able to find a decent use case for `with` 🤣 I knew it was gonna be needed sooner or later.
