### ISSUE TITLE
Sealing

### ISSUE THREAD

**Issue by Econ441** [h3rald/min#134]
```d
$ (scope puts "!" sealed-symbol?) =>
{;module}
 (
   {;module}
   true
  )
```

Why did it show `true`? Because i didn't define any symbol in the scope of quot.

I am scaring to use **scopes** 😱

**Comment by h3rald** [comment]
Well, if it doesn't find the symbol in the current scope it goes up the scope chain...

**Comment by Econ441** [comment]
> Well, if it doesn't find the symbol in the current scope it goes up the scope chain...

This isn't what we expected from it.

**Comment by h3rald** [comment]
Well... it may seem unusual but if that didn't work that way, you wouldn't be able to use those methods inside foreach, while, map etc. it works in the same way as lexical scoping: if the symbol is not found, it goes up the scope chain.
