### ISSUE TITLE
Wrong Error Location

### ISSUE THREAD

**Issue by Econ441** [h3rald/min#135]
I did:

```
( symbol use-as
    (int :n 'sym :fun ==> string :r)
    (
        n  fun ->  @r
    )
) ::


5 (pred) use-as puts
```

Error:

```
(!) vulcan.min(15,4) [::]: Invalid type 'string' specified in signature at position 6
    vulcan.min(15,4) in symbol: operator
    vulcan.min(15,4) in symbol: ::
```

The error says problem located at `(15,4)` **not** `(18, 11) [use place of symbol]`
Because i trust my symbol.

**Comment by h3rald** [comment]
Well, the error is there though 😊 it's `str` instead of `string` as of 0.31.0.

The reason why it doesn't say the error is where the symbol was used is because... the interpreter never got there, it stopped right at the incorrect operator definition.
