### ISSUE TITLE
Function requests: read & parse

### ISSUE THREAD

**Issue by mwgkgk** [h3rald/min#14]
Currently there is no way to parse a string into a quoted expression without interpreting it. `eval` parses and interprets a string, and `load` parses and interprets a file.

Scheme-like `read` would parse a file into a quoted expression without interpreting it. A `parse` function would parse a string into a quoted expression without interpreting it. `int` and `float` already do that for ints and floats, so this would behave similarly but for quotes.

**Comment by h3rald** [comment]
Mmmm ok, I see your point. OK, they make sense and they will be a useful addition to the lang module. Thanks for the suggesion!
