### ISSUE TITLE
i can't get symbol from root

### ISSUE THREAD

**Issue by ghost** [h3rald/min#140]
I can't get symbol from root:

```bat
$ (symbol addOne (int :n ==> int :r)(n succ @r)) ::
 0
$ ROOT /addOne
(!) <repl>(1,12) [/addOne]: Key 'addOne' is set to a native value that cannot be retrieved.
    <repl>(1,12) in symbol: dget
    <repl>(1,12) in symbol: /addOne
```

It says "native"

**Comment by h3rald** [comment]
Uhm it kinda makes sense now, but it should be properly documented and maybe not called "native".

Basically, at present:
* dget is for values (and lambdas)
* invoke is for... everything?

Does invoke work? I should check how dget is implemented, I understand this may seem confusing.

**Comment by Econ441** [comment]
I wrote `*ROOT/addOne` in terminal after declaring `addOne` symbol and *min interactive shell* didn't response. Is this a bug?

**Comment by h3rald** [comment]
Errrr 😳🙄 maybe?😬

Will have a look...

**Comment by h3rald** [comment]
This could be nasty.

I tried defining your operator and using it normally... It works as expected, but if I use `*ROOT/addOne` it gets stuck. It happens both in the shell and even when interpreting a file!

It looks like it's waiting for input, but I suspect there's some sort of recursion going on but I don't know why.

If you enable debug logs it looks like the method gets executed properly but then it never pushes the result to the stack:

![image](https://user-images.githubusercontent.com/1169/107131060-b6d91400-68d3-11eb-8854-6307fee73553.jpeg)

**Comment by Econ441** [comment]
How could i do operator modifying on defined operator signatures?

**Comment by h3rald** [comment]
Operators are not sealed by default, you can just overwrite it with another definition or a lambda...

**Comment by Econ441** [comment]
> Operators are not sealed by default, you can just overwrite it with another definition or a lambda...

However i couldn't have accessed their essences (quotes).

**Comment by h3rald** [comment]
Fixed
