### ISSUE TITLE
(!) No documentation found for symbol or sigil: integer

### ISSUE THREAD

**Issue by ghost** [h3rald/min#151]
I found a forgotten and alone... symbol: 😄 

```
$ ?integer
(!) No documentation found for symbol or sigil: integer
```

Looks like `integer` symbol has no help documentation.

`$ 1.2 integer` gives `1` It is used to convert `float` values to `int` values.

*Addition Note:* `integer` and `float` symbols haven't descriptive names. They should renamed as 
`to-int` `to-flt` or `toInt` `toFlt`

**Comment by h3rald** [comment]
Well spotted, will fix. As for the name change... naaah, it's fine. Don't wanna change them all again!

**Comment by h3rald** [comment]
Fixed.
