### ISSUE TITLE
square symbol / with symbol - bug

### ISSUE THREAD

**Issue by ghost** [h3rald/min#152]
I interpreted below lines and *min interactive shell* shut itself down.

```
$ (dup *) ^square
$ (5 square puts!) {} 'square %square with
```

Another exit way from min opened 😄

**Comment by Econ441** [comment]
Hey! Please fix it. Then, Do you know how are symbols be binded to scopes? Could you tell me how?

**Comment by h3rald** [comment]
I finally understood what is going on here, and I am not sure that technically is a bug: it's another recursion problem.

If you rename the key of your dictionary to something else than "square" (the name of your lambda) everything works as expected.

Here's what is going on... it is actually easier to reproduce as follows:

```
(dup *) ^square
{} 'square %square ; <-- this shouldn't be allowed!
:d
3 *d/square
```

Basically, the invoke (or `with` in your case) is evaluating the symbol `square` within the scope of `d`. 

Alright, so what's the value of `square`? Well... a quotation containing `square` that gets evaluated within the context of `d`.

Alright, so what's the value of `square`? Well... a quotation containing `square` that gets evaluated within the context of `d`.

...

I am not sure if I can prevent this from happening: I could check if you are trying to bind a quoted symbol which has the same value as the key, but I am not sure it's enough. Definitely it is going to cause trouble, so probably it shouldn't be allowed...

**Comment by h3rald** [comment]
It even works without a lambda!!! ![image](https://user-images.githubusercontent.com/1169/107159886-19ddb000-6993-11eb-9411-ba5f05916cde.jpeg)

**Comment by h3rald** [comment]
Fixed.
