### ISSUE TITLE
Zero Tetris - Bug

### ISSUE THREAD

**Issue by Econ441** [h3rald/min#153]
I found a game in min. It's easy to play the game: It is ... Zero Tetris Game!

# How do you play?

Just type `(true) (!"cls") while` after typing `'debug loglevel` in prompt, *if you're in Windoes*

You will see:

![ZeroTetrisGame](https://user-images.githubusercontent.com/78199412/107158219-bc009680-6999-11eb-9f41-a29153fddd83.png)

If you would like to exit from game then interrupt the shell => **Game Over!**

_________

This is the potential of min. There are a lot of possible examples to do with min. That is one of them.

... I hope you understood what goes on. A bug who i don't really know what type of bug occured.

After this... i like **interruption** more! (it saved my pc) 👍  That laggy game scared me a little bit. 😨

**Comment by h3rald** [comment]
Please do not deliberately try to break things. 

This is a project I am working on in my spare time, and my spare time is not that much, I don't have time for this.
