### ISSUE TITLE
Docs: extraneous "debug" declaration

### ISSUE THREAD

**Issue by mwgkgk** [h3rald/min#16]
```
debug

∅ ⇒ ∅

Toggles debug mode.
```

This conflicts with:
```
debug

a ⇒ a

Prints a and a new line to STDOUT, if logging level is set to debug or lower.
```
Couldn't find the first one in sources. Debug mode is in practice toggled with `'debug loglevel`.

**Comment by h3rald** [comment]
Well spotted. And debug? doesn't exist anymore either. There used to be a "debug mode" once, but then I removed in favor of the new logger.
