### ISSUE TITLE
Fails to install on mac

### ISSUE THREAD

**Issue by chadams** [h3rald/min#192]
I was able to install nim fine. `brew install nim`
but `nimble install min` resulted in 
```
Build failed for 'min@0.43.0', would you like to try installing 'min@#head' (latest unstable)? [y/N]
```
>y
```
...
Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      _BIO_socket_wait in libcrypto.a(libcrypto-lib-bio_sock.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of an external program failed: 'clang   -o '/var/folders/67/wfzhw4sd3gx30wh097_g8dfh0000gn/T/nimble_57863/githubcom_h3raldmin_#head/min' 
...
```

**Comment by h3rald** [comment]
Uhm that's weird. I was able to build the executable for macOS and also rebuild it myself on my Mac.

Could you:

- try to see if the prebuilt macOS executable runs on your machine? 
- try to clone the min repository and run `nimble build` from the root folder?

That error seems to be related to the OpenSSL/crypto library, which I pre-build for win/mac/linux and it is supposed to be linked statically when building min. I am wondering if for some reason when running nimble@ install it is not finding the prebuilt libcrypto.a file and pointing to something else (a different version of OpenSSL maybe).

What version of macOS are you using? Also the architecture is x64, it seems, right?

**Comment by chadams** [comment]
macOS Big Sur 11.7.8 2.5 GHz Quad-Core Intel Core i7 x64
I am able to use the prebuilt binary, I'll investigate some more, probably on my side then.
