### ISSUE TITLE
Getting the entire stack as a list

### ISSUE THREAD

**Issue by Ajusa** [h3rald/min#20]
How would I go about doing that? I tried concating in a loop, but I can't concat things that are ints.

Sorry if this is in the docs, I may not have seen that bit.

**Comment by h3rald** [comment]
Hi! 

Sure, no worries: you can use the `get-stack` symbol to get the entire contents of the stack as a quotation.

There are also a few other symbols to manipulate the stack as well, described here:

<https://min-lang.org/reference-stack/>

I should probably add a search functionality on the site, really... I understand it may be difficult to find things! Hope it helps!

**Comment by Ajusa** [comment]
Thanks!
