### ISSUE TITLE
How to slice a string? And way how not to do that.

### ISSUE THREAD

**Issue by Crutiatix** [h3rald/min#24]
I can't find any way how to slice string. There isn't any function in the _str module_ for this purpose.

My idea was at first to _split_ a string a char by char into strings in a quote and then _get_ or _slice_ it by functions from _seq module_ however when I try to do so system gets stuck as if it gets into endless loop. The problem is propably that I wanted to split string by empty string:
```
"abcdefgh" "" split
```
How can I slice string by another way? (by which I don't have to insert delimiters between every char)

Thanks

**Comment by h3rald** [comment]
Mmmm yep, you are right:

* there is currently no operator for slicing strings
* that behavior with `split` is most definitely a bug

If I get a chance this weekend I will fix the `split` method and also maybe implement a new `substr` operator for slicing strings.

I am thinking of something like:

```
"wonderful" 0 6 substr 
```

...which would output `wonder`.
