### ISSUE TITLE
`load` conflicts with `cd`

### ISSUE THREAD

**Issue by mwgkgk** [h3rald/min#26]
To reproduce:
> root/file1.min
```
"File 1 loaded!" puts!
```
> root/dir1/file2.min
```
("file2.min" file?) (args first dirname cd) unless

"../file1" load
```
Error scenario:
```
min root/dir1/file2.min
(!) root/dir1/file2.min(3,15) [load]: File 'root/dir1/../file1.min' does not exists.
    root/dir1/file2.min(3,15) in symbol: load
```
No problems when run without cd, from the exact dir like the code above suggests, or, without the "unless" line, from anywhere. It's the cd that messes it up. `fread`, `fappend`, `fwrite`, and even `read` (!!) don't conflict with cd under this scenario.

Error message typo: "does not exists" should be "does not exist".

Like always, big fan of this project. :1st_place_medal:

**Comment by h3rald** [comment]
Very strange. I'll investigate and fix it...

Thanks for your input, as usual! :)
