### ISSUE TITLE
'withScope' does not return old scope on exception

### ISSUE THREAD

**Issue by Esgorhannoth** [h3rald/min#27]
While playing in REPL, I typed something like this
```
[path]$ ("a string" puts!") ->
(!) <repl>(1,14) [puts!"]: Undefined symbol 'puts!"'
    <repl>(1,14) in symbol: puts!"
    <native> in symbol: dequote
    <repl>(1,18) in symbol: ->
```
and after that Tab-completion stopped working. So I got my nose into the source and found out that the template withScope in core/interpreter.nim does not handle exceptions in ```body``` passed to it.
I suggest wrapping body and scope restoring lines in ```try...finally```.

**Comment by h3rald** [comment]
Thanks! Fixing now...
