### ISSUE TITLE
`(dup *) square define` -> Undefined symbol 'square'

### ISSUE THREAD

**Issue by enthus1ast** [h3rald/min#3]
at https://min-lang.org/learn-operators/
```
z@z ~/min> ./min -i
[/home/z/min]$ 1
{1} -> 1
[/home/z/min]$ 2
{2} -> 2
[/home/z/min]$ (dup *) square define
(!) <repl>(1,14) [square]: Undefined symbol 'square'
    <repl>(1,14) in symbol: square
[/home/z/min]$ 
```

**Comment by enthus1ast** [comment]
`(dup *) 'square define` 
?

**Comment by h3rald** [comment]
Yep... right, any of the following:

`(dup *) 'square define` 

or

`(dup *) "square" define` 

...of course probably once you get the hang of sigils you'd probably go for just:

`(dup *) :square` 

I'll fix it right now, thanks for spotting this!
