### ISSUE TITLE
Error: 'typedesc' metatype is not valid here; typed '=' instead of ':'?

### ISSUE THREAD

**Issue by cstrotm** [h3rald/min#39]
I'm trying to compile min with NIM 020

```
Nim Compiler Version 0.20.0 [Linux: i386]
Compiled at 2019-06-06
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: e7471cebae2a404f3e4239f199f5a0c422484aac
active boot switches: -d:release
```

and I'm getting this error
```
min/packages/nim-miniz/src/nim_miniz.nim(244, 21) Error: 'typedesc' metatype is not valid here; typed '=' instead of ':'?
```

I'm new to NIM and "min" and can't find what is wrong here. As the "min" code has not been changed for some time, it might be a regression with the new NIM compiler version.

**Comment by h3rald** [comment]
Hi! Yes, this was indeed a regression, which I fixed in nim-miniz. 

You can try running `nifty upgrade` and then recompile min, and it will hopefully work.
