### ISSUE TITLE
old binaries

### ISSUE THREAD

**Issue by zenon** [h3rald/min#41]
https://min-lang.org/download/
still points to min 0.19.4 which I recognised because the windows build seems to be broken.

**Comment by h3rald** [comment]
Well spotted! Well, this weekend perhaps I'll find some time to give min some love... thanks for reporting this, will fix it 😊👍

**Comment by zenon** [comment]
Wow, you respond fast! :-)

**Comment by h3rald** [comment]
Fixed now, thanks again.
