### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by zenon** [h3rald/min#45]
Hi Fabio,

I pulled min, and tried to 

nim c -d:release min.nim

again. Got the following error:

Hint: min_math [Processing]
lib/min_math.nim(34, 5) Error: undeclared identifier: 'formatValue'

(As I don't know Nim yet, I don' know where to look.)

(Linux Debian)

Kind greetings.

z.

**Comment by SolitudeSF** [comment]
what's your nim version?

**Comment by zenon** [comment]
Nim Compiler Version 0.19.4

**Comment by SolitudeSF** [comment]
thats pretty old, could you try with the latest version?

**Comment by zenon** [comment]
I'll try. Thank you for the advise! :-)

**Comment by zenon** [comment]
Works! Thank you!

(I had to add the link for /usr/local/bin/x86_64-linux-musl-gcc but then it worked.)

And this way the 

    SIGSEGV: Illegal storage access. (Attempt to read from nil?)

I mentioned in https://github.com/h3rald/min/issues/43 vanished too. HTTP works now for me under Linux too.

**Comment by h3rald** [comment]
Oh well nothing to do here 😊 

Thanks @SolitudeSF! And yes, that was a small change I made to fix a deprecation notice...
