### ISSUE TITLE
no echo

### ISSUE THREAD

**Issue by zenon** [h3rald/min#46]
Hello,

after I compiled min some days ago, I just tested the web example and left it.
Now, I find that the REPL stopped echoing the keys I type. So after pressing ENTER, I see the results, but I can't see what I type.

Debian Linux (Windows 10 Linux Subsystem), Nim 1.1.1

I can't tell if this is anything related to min. But I don't know anywhere else to ask.
Any ideas?

Kind greetings, z.

**Comment by h3rald** [comment]
Mmmmm nasty. Probably something broken with [nimline](https://github.com/h3rald/nimline) I guess... I'll have a look on my linux system.

**Comment by h3rald** [comment]
I updated nimline yesterday for another problem, possibly related, and then installed min in WSL, like you did, and everything seems to work as expected...

![image](https://user-images.githubusercontent.com/1169/73057694-6f334600-3e92-11ea-92a4-6c76d0eac5cf.png)

**Comment by zenon** [comment]
Hm. I almost assumed this would be something with my configuration. Thank you for checking!
