### ISSUE TITLE
Silent ignore of odd entry in dict

### ISSUE THREAD

**Issue by zenon** [h3rald/min#47]
{1 :uno 2 :due 3}

gives

{1} -> {
         2 :due
         1 :uno
       }

without any error message, i.e. the leftover 3 is just ignored. I think this is not a good idea. It is not exactly a bug, but I suggest to add the feature of giving an error message here.

**Comment by h3rald** [comment]
Well spotted! I am now raising an error in case dictionaries are unbalanced like in your case. Thanks!

(change will be included in next release)
