### ISSUE TITLE
non funct download links

### ISSUE THREAD

**Issue by zenon** [h3rald/min#51]
In https://min-lang.org/download/ the download links don't work.

Right:
https://github.com/h3rald/min/releases/download/0.19.6/min_v0.19.6_linux_x64.zip

Wrong, and current:
https://github.com/h3rald/min/releases/download/v0.19.6/min_v0.19.6_linux_x64.zip
(the v in the first version number is not correct)

**Comment by h3rald** [comment]
Fixed... the incorrect format was actually in the release name...
