### ISSUE TITLE
Feature: Access to log level

### ISSUE THREAD

**Issue by zenon** [h3rald/min#53]
I can set the loglevel at runtime. Can I read it too?

**Comment by h3rald** [comment]
Fair enough...

**Comment by h3rald** [comment]
`loglevel?` exists but actually prints it... mmm I wonder why I did this... BUT it's undocumented! Alright, I'll change its behavior to push the current log level on the stack. Technically a breaking change but:

a) min is still 0.x
b) It was apparently an undocumented symbol...
