### ISSUE TITLE
Prelude, question, probably a feature request

### ISSUE THREAD

**Issue by zenon** [h3rald/min#55]
I see a prelude.min in the project, but no place where it is loaded. Is it?

If yes, can I load a changed prelude instead? (e.g. using a runtime option, like, -p:prolog2.min)

**Comment by h3rald** [comment]
Yeah I like it. At present is literally included in the executable... but yes, it should be configurable.

**Comment by h3rald** [comment]
Added... but gotta document it properly and explain what the standard prelude contains.
