### ISSUE TITLE
dynamic libraries, feature request

### ISSUE THREAD

**Issue by zenon** [h3rald/min#56]
Sorry for spamming. This is the last for today :-)

I can give min the option to (un)install a dynamic library. To find out which ones are loaded,
I have to look at $HOME/.minlibs/ (%HOMEPATH%\.minlibs\ on Windows. 

Is there a way to find out from inside min?

I imagine two functions

dynlib? : string/symbol -> bool
dynlibs : empty -> list of symbols

**Comment by h3rald** [comment]
LOL @ "for today"

Yes! Agreed. I'll add them. 

Out of curiosity... did you manage to get a dynamic library to work? On what system? (See #13)

**Comment by zenon** [comment]
Ah. No. This was a thought while reading the documentation.

**Comment by h3rald** [comment]
Closing as dynamic support has been removed. At least until there's a way to implement it tidily in a cross-platform way.
