### ISSUE TITLE
Unbuffered input from STDIN

### ISSUE THREAD

**Issue by agentofuser** [h3rald/min#59]
The `gets` symbol reads one line at a time. Is there a way to get unbuffered input immediately on every keystroke? Like if I want to write a repl in min itself and handle keybindings. Thanks!

**Comment by h3rald** [comment]
That's definitely doable, I'll expose nimline's **getchr** and **putchr** methods, those should help with your use case 😄

**Comment by agentofuser** [comment]
Perfect, thank you! :)
