### ISSUE TITLE
lib/min_time.nim(56, 27): Error: the field 'second' is not accessible.

### ISSUE THREAD

**Issue by agentofuser** [h3rald/min#61]
I'm getting this error when running `nim c min.nim` (with or without release or ssl flags) on a raspi4b (armhf).

I'm using the latest nim version:

```
Nim Compiler Version 1.3.5 [Linux: arm]
Compiled at 2020-06-27
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: f926dc53f127cb7fc26daf35e0de38612a512552
active boot switches: -d:release
```

**Comment by h3rald** [comment]
Mmm... I guess something will change in the next version of Nim concering TimeInfo... On Nim 1.2.6 runs fine, I am not planning to support Nim 1.3.* until it comes out really. Closing for now.

**Comment by agentofuser** [comment]
Oh, I didn't know min required nim 1.2. I downgraded it, and it worked, thank you! =)

**Comment by h3rald** [comment]
Reopening, this is now an issue with Nim v1.4.0
