### ISSUE TITLE
cannot start min

### ISSUE THREAD

**Issue by odtaa48** [h3rald/min#62]
Hello
I have a fairly vanilla linux box
uname -a -> Linux librem15 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux).
However when I start min, unzipped from min_v0.20.0_linux_x64.zip, I get:
bash: ./min: No such file or directory
Can anyone help.
I get the same thing on a chromebook terminal.
Many thanks for a great looking product.

**Comment by h3rald** [comment]
Found the problem, it was due to a missing flag while cross-compiling for linux (basically it looks for musl, but it should have been statically compiled instead). Will release a fix soon.

**Comment by h3rald** [comment]
Fixed in 0.20.1.
