### ISSUE TITLE
v0.20.1 issue

### ISSUE THREAD

**Issue by odtaa48** [h3rald/min#63]
Hello, thanks for the updated binary for linux, however, it appears that there is something different in the REPL that happened between 19.3 and the current version using _min -i_

The prompt only appears AFTER enter is pressed, and what is typed is invisible and so are the features like command completion.  The input seems to be interpreted correctly, however.

I don't think the shell is an issue, as  I get the same results on tilix and my chromebook virtual linux shell which I think is dash.

$ min -i
[/home/odtaa/Downloads]$ 
[/home/odtaa/Downloads]$ version
 "0.20.1"
[/home/odtaa/Downloads]$ cpu
 "amd64"
[/home/odtaa/Downloads]$ os
 "linux"

min -j has other issues where it seems to stack the prompt again and again;
 it also seems to have the following error after ctrl-D:
io.nim(141)              raiseEOF
Error: unhandled exception: EOF reached [EOFError]

Best regards, Dex

**Comment by h3rald** [comment]
Hi!

You are right, there seems to still be problems with the cross-compiled binary. I think at this point I'll just compile it on my actual Linux machine instead: I don't have any issue if I natively try to compile on linux.

**Comment by odtaa48** [comment]
Hi, thanks for getting back.
I don't recall all the issues, but I found the native compilation (installation also) tricky so gave up.
I think you have the best concatenative product here. I found factor too arduous.
Cheers
-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Sep 29, 2020, 03:41 by notifications@github.com:

**Comment by h3rald** [comment]
Thanks! 😄 

Well, there are a few dependencies that are needed to build min, and you need to have [nifty](https://h3rald.com/nifty) installed to fetch them... also compiling/installing via nimble may not work.

I am working on a small update to fix a few bits, I'll release native binaries this time if I get a chance.

About Factor... well, Factor docs are very good, but it is indeed quite complex. I wanted to keep min small while at the same time provide a decent feature set. Concatenative programming *is* complex anyway, no matter how you look at it, but it's also quite stimulating at times!

**Comment by h3rald** [comment]
This should be fixed in v0.21.0... now providing non cross-compiled binaries for windows and linux as well.

**Comment by h3rald** [comment]
I figured out what was happening. It turns out that in the musl library, stdout.write doesn't automatically flush the stdout buffer... so characters were only appearing when a new line was entered.

I modified some nimline code and now it works as expected.
