### ISSUE TITLE
`neg` Symbol Needed

### ISSUE THREAD

**Issue by baykus871** [h3rald/min#81]
Does a symbol like `neg` that negatives given numbers exist in Min?

-1 => 1
-inf => inf

?????

**Comment by baykus871** [comment]
I write a func but this is not the **efficient** way.

**Comment by h3rald** [comment]
Hmm basically multiplying by -1, right? Sure, I'll add it... and I'll add `abs` as well, because it's missing too!

**Comment by baykus871** [comment]
There are some math tools missing. Yes one of is `abs`. I don't think even to multiplying the number by `-1`. MY faulting again. My symbol includes `eval`. I thought hard way.

**Comment by h3rald** [comment]
Thinking about it... I am not gonna add a neg symbol, as yes multiplying by -1 would give you the right result... but I am gonna add abs anyway.

**Comment by h3rald** [comment]
Fixed in v0.29.0
