### ISSUE TITLE
Code In Commenting

### ISSUE THREAD

**Issue by baykus871** [h3rald/min#86]
You are going to add `#| ... |#`. Now, i think there should be one more begin-end commentation like `Q| ... |Q`. If you do that then i will be able to introduce it to *Notepad++ Min Extension*.

What it brings to us?

I can except `Q| ... |Q` from commenting style.
Thereafter:

`#| ... |#` => Comment Style
`Q| ... |Q` => Code Style(No-Comment Style)

This will enable to documentate **code examples** within multi-line comments.

You should make another string declaration like as backticks (\`\`).

I will except it from string-styling if you add it.

**Comment by h3rald** [comment]
Uhm... not sure I like `Q| ... |Q` for... documentation comments, is that what you mean? 

I wanted to make it similar to lisp/scheme comments (hence `;` are used for single line comments) but multi-line comments are rare in lisp/scheme, and for documentation they seem to use multiple `;`, which is not great.

Maybe `#|| ... ||#` instead? 

And why would you add backticks exactly? What would they be used for? Can you write an example?

documentation comments imply a documentation generator.... 😱 that's a whole project by itself.

**Comment by baykus871** [comment]
No no. I cannot explain it in Github because of non-hightlighting.

**Comment by baykus871** [comment]
> documentation comments imply a documentation generator.... 😱 that's a whole project by itself.

There are things which chained to each other.

Code Examples without Comment Highlighting In Comments
<Chained To>
Code Documentation for Symbol Usage

**Comment by baykus871** [comment]
> `#|| ... ||#`

Okay, good! 👍

**Comment by h3rald** [comment]
> No no. I cannot explain it in Github because of non-hightlighting of Github for Min.

```scheme
; Scheme highlighting half works for min ;)
"Test" :test
(1 2 3 4) 'puts foreach
```

...but unfortunately not even GitHub highlighters for lisp or scheme recognize `#| ...  |#` for block comments 😞 because they don't seem to be that popular.

**Comment by baykus871** [comment]
> > No no. I cannot explain it in Github because of non-hightlighting of Github for Min.
> 
> ```scheme
> ; Scheme highlighting half works for min ;)
> "Test" :test
> (1 2 3 4) 'puts foreach
> ```
> 
> ...but unfortunately not even GitHub highlighters for lisp or scheme recognize `#| ... |#` for block comments 😞 because they don't seem to be that popular.

Yeah, there are some extensions who i know and that is made: *VSCod Min Hghl.* *Vim Min Hghl.* *Notepad++ Min Hghl.*.
this is what we can do. 🤒 

Brr. Cold is everywhere and Github too. No highlighting isn't a problem for don't preffering Github, methinks. 😄 

A look at: https://github.com/github/linguist
